```{r, include=FALSE}
# Nettoyage de l'environnement
rm(list = ls())

# Définition du répertoire de travail
setwd("/home/rogerbernat/Documents/Projet_statistique_2024")

# Chargement du fichier .rds
donnees <- readRDS("supp_p_val_10.Rdata", "rb")
var_p_val <- readRDS("variables_selectionnees_p_valeur.Rdata", "rb")
nrow(var_p_val)
load("supp_p_val_10_clem.Rdata")
donnees <- bdd_apres_pvalue_10
```

# Affichage répartition selon variable à expliquer
Commençons avec variables qualitatives:

```{r}

factor_var <- colnames(donnees)[sapply(donnees, FUN= function(x){is.factor(x)})]


for (col in factor_var) {
    # On parcourt les noms des variables
  if (!(col %in% c("y", "CODE_ELEVAGE"))) {  # Si la colonne n'est pas la colonne y ou CODE_ELEVAGE
    cat("Tableau de contingence entre les variables y et", col, ":\n") 
    print(table(donnees$y, donnees[[col]])) # Affichage tableau de contingence
    cat("\n")  # Ajoute ligne vide pour une meilleure lisibilité
  }
}
```

Continuons avec variables quantitatives:
```{r}
# On crée un vecteur contenant le nom des variables numeric
numeric_var <- colnames(donnees)[sapply(donnees, FUN= function(x){is.numeric(x)})]
for (col in numeric_var) {
    # On parcourt les noms des variables
  if (!(col %in% c("y", "CODE_ELEVAGE"))) {  # Si la colonne n'est pas la colonne y ou CODE_ELEVAGE
    cat("Boxplot entre les variables y et", col, ":\n") 
    boxplot(donnees[[col]] ~ donnees$y, outline=F) # Affichage tableau de contingence
  }
}
```
```{r, include=F, eval=F}
ncol(donnees)
saveRDS(var_p_val, "df_var_p-val.Rdata")
saveRDS(donnees, "suppression_doublons.Rdata")
```
