
```{r}
data <- readRDS("/home/rogerbernat/Documents/ENSAI/ensai 2024-25/Projet_statistique_2024/supp_redondanceet+tutrice_new.Rdata")
length(data)
data.missing <- data[-c(1)]
names(data.missing)

```

```{r}
blue <- rgb(189, 215, 238, maxColorValue = 255)
orange <- rgb(255, 154, 53, maxColorValue = 255)
heatmap_missing_base <- function(df, color1 = "white", color2 = "red") {
  # Create a matrix to represent missing (1) and non-missing (0) values
  missing_matrix <- is.na(df)
  
  # Transpose the matrix
  missing_matrix <- missing_matrix
  
  # Set up plotting area
  par(mar = c(5, 14, 2, 2))
  image(missing_matrix[, ncol(missing_matrix):1], 
        col = c(color1, color2), 
        axes = FALSE, 
        xlab = "Individus", 
        ylab = "", 
        main = "")
  
  # Add axis labels
  axis(1, at = seq(0, 1, length.out = nrow(df)), labels = seq_len(nrow(df)), las = 2)
  axis(2, at = seq(0, 1, length.out = ncol(df)), labels = rev(colnames(df)), las = 2)
  
  # Add legend
  legend("topright", legend = c("Données non-manquantes", "Données manquantes"), fill = c(color1, color2), border = "black")
}


png("val_manq.png", height=850, width=850)
heatmap_missing_base(data.missing, color1 = blue,  color2 = orange)
dev.off()
```